FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
      tesseract-ocr \
      tesseract-ocr-ell \
      tesseract-ocr-eng \
      poppler-utils \
    && rm -rf /var/lib/apt/lists/*

COPY requirements/extractor.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY shared.py extractor.py ./

CMD ["python", "extractor.py"]
