FROM python:3.12-slim

WORKDIR /app

COPY requirements/downloader.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY shared.py downloader.py ./

CMD ["python", "downloader.py"]
