FROM python:3.12-slim

WORKDIR /app

COPY requirements/scraper.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ingestion/shared.py ingestion/scraper.py ./

CMD ["python", "scraper.py"]
